### ISSUE TITLE
XmlPullParserException

### ISSUE THREAD

**Issue by esiefker** [compomics/xilmass#1]
Running on Debian Sid.  I get this exception 
```

 Error: A JNI error has occurred, please check your installation and try again
 Exception in thread "main" java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException
 	at java.lang.Class.getDeclaredMethods0(Native Method)
 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
 	at java.lang.Class.getMethod0(Class.java:3018)
 	at java.lang.Class.getMethod(Class.java:1784)
 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
 Caused by: java.lang.ClassNotFoundException: org.xmlpull.v1.XmlPullParserException
 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
 	... 7 more

```

I have xmlpull-1.1.3.1.jar in my CLASSPATH.  
I also have XPP3 installed, which I gather is an implementation of xmlpull?  

```
hatta@biox:~/yoyo/XL-MS/xilmass-1.0$ echo $CLASSPATH
/usr/share/java/
hatta@biox:~/yoyo/XL-MS/xilmass-1.0$ ls /usr/share/java/*xmlp*
/usr/share/java/xmlpull-1.1.3.1.jar
/usr/share/java/xmlpull-1.1.3.4d_b4_min.jar
hatta@biox:~/yoyo/XL-MS/xilmass-1.0$ ls /usr/share/java/*xpp*
/usr/share/java/xpp2-2.1.10.jar  /usr/share/java/xpp3-min-1.1.4c.jar
/usr/share/java/xpp2.jar         /usr/share/java/xpp3-min.jar
/usr/share/java/xpp3-1.1.4c.jar  /usr/share/java/xpp3-xpath-1.1.4c.jar
/usr/share/java/xpp3.jar         /usr/share/java/xpp3-xpath.jar
```

This should work, right?  Am I doing something wrong?

**Comment by esiefker** [comment]
I was doing something wrong.  Reextracting the archive in a fresh directory fixed that problem.
